#include "InitKernel.hpp"
template <int Q>
__global__ void InitKernel(real_t* __restrict__ df,
                           int nx,
                           int ny,
                           int nz,
                           real_t rho,
                           real_t vx,
                           real_t vy,
                           real_t vz,
                           real_t T) {
  // Generated by lbm_gen_init.py
  real_t sq_term;
  sq_term = -1.5f * (vx) * (vx)-1.5f * (vy) * (vy)-1.5f * (vz) * (vz);
  Vector3<int> pos(threadIdx.x, blockIdx.x, blockIdx.y);
  if ((pos.x() >= nx) || (pos.y() >= ny) || (pos.z() >= nz)) return;
  const int x = pos.x();
  const int y = pos.y();
  const int z = pos.z();
  switch (Q) {
    case 7:
      df[I4D(0, x, y, z, nx, ny, nz)] = 0.14285714285714285f * T;
      df[I4D(1, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (3.5f * vx + 1.0f);
      df[I4D(2, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (1.0f - 3.5f * vx);
      df[I4D(3, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (3.5f * vy + 1.0f);
      df[I4D(4, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (1.0f - 3.5f * vy);
      df[I4D(5, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (3.5f * vz + 1.0f);
      df[I4D(6, x, y, z, nx, ny, nz)] =
          0.14285714285714285f * T * (1.0f - 3.5f * vz);
      break;
    case 19:
      df[I4D(0, x, y, z, nx, ny, nz)] =
          0.33333333333333331f * rho * (sq_term + 1.0f);
      df[I4D(1, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vx) * (vx) + 3.0f * vx + 1.0f);
      df[I4D(2, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vx) * (vx)-3.0f * vx + 1.0f);
      df[I4D(3, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vy) * (vy) + 3.0f * vy + 1.0f);
      df[I4D(4, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vy) * (vy)-3.0f * vy + 1.0f);
      df[I4D(5, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vz) * (vz) + 3.0f * vz + 1.0f);
      df[I4D(6, x, y, z, nx, ny, nz)] =
          0.055555555555555552f * rho *
          (sq_term + 4.5f * (vz) * (vz)-3.0f * vz + 1.0f);
      df[I4D(7, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                        (sq_term + 3.0f * vx + 3.0f * vy +
                                         4.5f * (vx + vy) * (vx + vy) + 1.0f);
      df[I4D(8, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                        (sq_term - 3.0f * vx + 3.0f * vy +
                                         4.5f * (-vx + vy) * (-vx + vy) + 1.0f);
      df[I4D(9, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                        (sq_term + 3.0f * vx - 3.0f * vy +
                                         4.5f * (vx - vy) * (vx - vy) + 1.0f);
      df[I4D(10, x, y, z, nx, ny, nz)] =
          0.027777777777777776f * rho *
          (sq_term - 3.0f * vx - 3.0f * vy + 4.5f * (-vx - vy) * (-vx - vy) +
           1.0f);
      df[I4D(11, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                         (sq_term + 3.0f * vx + 3.0f * vz +
                                          4.5f * (vx + vz) * (vx + vz) + 1.0f);
      df[I4D(12, x, y, z, nx, ny, nz)] =
          0.027777777777777776f * rho *
          (sq_term - 3.0f * vx + 3.0f * vz + 4.5f * (-vx + vz) * (-vx + vz) +
           1.0f);
      df[I4D(13, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                         (sq_term + 3.0f * vx - 3.0f * vz +
                                          4.5f * (vx - vz) * (vx - vz) + 1.0f);
      df[I4D(14, x, y, z, nx, ny, nz)] =
          0.027777777777777776f * rho *
          (sq_term - 3.0f * vx - 3.0f * vz + 4.5f * (-vx - vz) * (-vx - vz) +
           1.0f);
      df[I4D(15, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                         (sq_term + 3.0f * vy + 3.0f * vz +
                                          4.5f * (vy + vz) * (vy + vz) + 1.0f);
      df[I4D(16, x, y, z, nx, ny, nz)] =
          0.027777777777777776f * rho *
          (sq_term - 3.0f * vy + 3.0f * vz + 4.5f * (-vy + vz) * (-vy + vz) +
           1.0f);
      df[I4D(17, x, y, z, nx, ny, nz)] = 0.027777777777777776f * rho *
                                         (sq_term + 3.0f * vy - 3.0f * vz +
                                          4.5f * (vy - vz) * (vy - vz) + 1.0f);
      df[I4D(18, x, y, z, nx, ny, nz)] =
          0.027777777777777776f * rho *
          (sq_term - 3.0f * vy - 3.0f * vz + 4.5f * (-vy - vz) * (-vy - vz) +
           1.0f);
      break;
    case 27:
      df[I4D(0, x, y, z, nx, ny, nz)] =
          0.29629629629629628f * rho * (sq_term + 1.0f);
      df[I4D(1, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vx) * (vx) + 3.0f * vx + 1.0f);
      df[I4D(2, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vx) * (vx)-3.0f * vx + 1.0f);
      df[I4D(3, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vy) * (vy) + 3.0f * vy + 1.0f);
      df[I4D(4, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vy) * (vy)-3.0f * vy + 1.0f);
      df[I4D(5, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vz) * (vz) + 3.0f * vz + 1.0f);
      df[I4D(6, x, y, z, nx, ny, nz)] =
          0.07407407407407407f * rho *
          (sq_term + 4.5f * (vz) * (vz)-3.0f * vz + 1.0f);
      df[I4D(7, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                        (sq_term + 3.0f * vx + 3.0f * vy +
                                         4.5f * (vx + vy) * (vx + vy) + 1.0f);
      df[I4D(8, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                        (sq_term - 3.0f * vx + 3.0f * vy +
                                         4.5f * (-vx + vy) * (-vx + vy) + 1.0f);
      df[I4D(9, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                        (sq_term + 3.0f * vx - 3.0f * vy +
                                         4.5f * (vx - vy) * (vx - vy) + 1.0f);
      df[I4D(10, x, y, z, nx, ny, nz)] =
          0.018518518518518517f * rho *
          (sq_term - 3.0f * vx - 3.0f * vy + 4.5f * (-vx - vy) * (-vx - vy) +
           1.0f);
      df[I4D(11, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                         (sq_term + 3.0f * vx + 3.0f * vz +
                                          4.5f * (vx + vz) * (vx + vz) + 1.0f);
      df[I4D(12, x, y, z, nx, ny, nz)] =
          0.018518518518518517f * rho *
          (sq_term - 3.0f * vx + 3.0f * vz + 4.5f * (-vx + vz) * (-vx + vz) +
           1.0f);
      df[I4D(13, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                         (sq_term + 3.0f * vx - 3.0f * vz +
                                          4.5f * (vx - vz) * (vx - vz) + 1.0f);
      df[I4D(14, x, y, z, nx, ny, nz)] =
          0.018518518518518517f * rho *
          (sq_term - 3.0f * vx - 3.0f * vz + 4.5f * (-vx - vz) * (-vx - vz) +
           1.0f);
      df[I4D(15, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                         (sq_term + 3.0f * vy + 3.0f * vz +
                                          4.5f * (vy + vz) * (vy + vz) + 1.0f);
      df[I4D(16, x, y, z, nx, ny, nz)] =
          0.018518518518518517f * rho *
          (sq_term - 3.0f * vy + 3.0f * vz + 4.5f * (-vy + vz) * (-vy + vz) +
           1.0f);
      df[I4D(17, x, y, z, nx, ny, nz)] = 0.018518518518518517f * rho *
                                         (sq_term + 3.0f * vy - 3.0f * vz +
                                          4.5f * (vy - vz) * (vy - vz) + 1.0f);
      df[I4D(18, x, y, z, nx, ny, nz)] =
          0.018518518518518517f * rho *
          (sq_term - 3.0f * vy - 3.0f * vz + 4.5f * (-vy - vz) * (-vy - vz) +
           1.0f);
      df[I4D(19, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term + 3.0f * vx + 3.0f * vy + 3.0f * vz +
           4.5f * (vx + vy + vz) * (vx + vy + vz) + 1.0f);
      df[I4D(20, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term - 3.0f * vx + 3.0f * vy + 3.0f * vz +
           4.5f * (-vx + vy + vz) * (-vx + vy + vz) + 1.0f);
      df[I4D(21, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term + 3.0f * vx - 3.0f * vy + 3.0f * vz +
           4.5f * (vx - vy + vz) * (vx - vy + vz) + 1.0f);
      df[I4D(22, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term - 3.0f * vx - 3.0f * vy + 3.0f * vz +
           4.5f * (-vx - vy + vz) * (-vx - vy + vz) + 1.0f);
      df[I4D(23, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term + 3.0f * vx + 3.0f * vy - 3.0f * vz +
           4.5f * (vx + vy - vz) * (vx + vy - vz) + 1.0f);
      df[I4D(24, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term - 3.0f * vx + 3.0f * vy - 3.0f * vz +
           4.5f * (-vx + vy - vz) * (-vx + vy - vz) + 1.0f);
      df[I4D(25, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term + 3.0f * vx - 3.0f * vy - 3.0f * vz +
           4.5f * (vx - vy - vz) * (vx - vy - vz) + 1.0f);
      df[I4D(26, x, y, z, nx, ny, nz)] =
          0.0046296296296296294f * rho *
          (sq_term - 3.0f * vx - 3.0f * vy - 3.0f * vz +
           4.5f * (-vx - vy - vz) * (-vx - vy - vz) + 1.0f);
      break;
  }
}
template __global__ void InitKernel<7>(real_t* __restrict__ df,
                                       int nx,
                                       int ny,
                                       int nz,
                                       float rho,
                                       float vx,
                                       float vy,
                                       float vz,
                                       float T);

template __global__ void InitKernel<19>(real_t* __restrict__ df,
                                        int nx,
                                        int ny,
                                        int nz,
                                        float rho,
                                        float vx,
                                        float vy,
                                        float vz,
                                        float T);

template __global__ void InitKernel<27>(real_t* __restrict__ df,
                                        int nx,
                                        int ny,
                                        int nz,
                                        float rho,
                                        float vx,
                                        float vy,
                                        float vz,
                                        float T);
