

// Generated by lbm_gen_ddqq_indexing.py
real_t f0 = df3D(0, x, y, z, nx, ny, nz);
real_t f1 = df3D(1, xm, y, z, nx, ny, nz);
real_t f2 = df3D(2, xp, y, z, nx, ny, nz);
real_t f3 = df3D(3, x, ym, z, nx, ny, nz);
real_t f4 = df3D(4, x, yp, z, nx, ny, nz);
real_t f5 = df3D(5, x, y, zm, nx, ny, nz);
real_t f6 = df3D(6, x, y, zp, nx, ny, nz);
real_t f7 = df3D(7, xm, ym, z, nx, ny, nz);
real_t f8 = df3D(8, xp, ym, z, nx, ny, nz);
real_t f9 = df3D(9, xm, yp, z, nx, ny, nz);
real_t f10 = df3D(10, xp, yp, z, nx, ny, nz);
real_t f11 = df3D(11, xm, y, zm, nx, ny, nz);
real_t f12 = df3D(12, xp, y, zm, nx, ny, nz);
real_t f13 = df3D(13, xm, y, zp, nx, ny, nz);
real_t f14 = df3D(14, xp, y, zp, nx, ny, nz);
real_t f15 = df3D(15, x, ym, zm, nx, ny, nz);
real_t f16 = df3D(16, x, yp, zm, nx, ny, nz);
real_t f17 = df3D(17, x, ym, zp, nx, ny, nz);
real_t f18 = df3D(18, x, yp, zp, nx, ny, nz);
real_t T0 = Tdf3D(0, x, y, z, nx, ny, nz);
real_t T1 = Tdf3D(1, xm, y, z, nx, ny, nz);
real_t T2 = Tdf3D(2, xp, y, z, nx, ny, nz);
real_t T3 = Tdf3D(3, x, ym, z, nx, ny, nz);
real_t T4 = Tdf3D(4, x, yp, z, nx, ny, nz);
real_t T5 = Tdf3D(5, x, y, zm, nx, ny, nz);
real_t T6 = Tdf3D(6, x, y, zp, nx, ny, nz);
